<?php 
$_DATABASEHOST = '192.168.1.27';
$_DATABASEUSER = 'admin';
$_DATABASEPASSWORD = '5852151661';

$mysqli = mysqli_connect($_DATABASEHOST, $_DATABASEUSER, $_DATABASEPASSWORD, "DBMOAUTH2");
?>